server:
  port: 8086
spring:
  jpa:
    properties:
      database: mysql
      database-platform: mysql
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL57Dialect
      show-sql: true
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    password: 123456
    url: jdbc:mysql://localhost:8066/TESTDB?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
