server:
  port: 8033
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/gang?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hbm2ddl:
          auto: none
    show-sql: true

