gang:
  name: ant-black
  url:  https://blog.csdn.net/zzg19950824
  test:
    name: gang
    age: 2
    testList:
      - test001
      - test002
    cfgEntities:
      - username: 11111
        userage: 2
      - username: 22222
        userage: 3
    cfgMap:
      gang: loveZhang
      zhang: loveGnag
    cfgEntityMap:
      gang: {
        username: 11123,
        userage: 21
      }
server:
  port: 8085
