spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gang?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

