server:
  port:8000
spring:
  jpa:
    # 是否生成ddl语句
    generate-ddl: false
    # 是否打印sql语句
    show-sql: true
    # 自动生成ddl，由于指定了具体的ddl，此处设置为none
    hibernate:
      ddl-auto: none
  datasource:
    # 使用H2数据库
    platform: h2
    # 指定生成数据库的schema文件位置
    schema: classpath:schema.sql
    # 指定插入数据库语句的脚本位置
    data: classpath:data.sql
    #  数据库地址
    url: jdbc:h2:D:\database\h2\data
    #数据库驱动
    driver-class-name: org.h2.Driver
    #数据库用户名
    username: root
    #数据库密码
    password: 123456
  h2:
    console:
      settings:
        # 进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
        web-allow-others: true
        #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。
      path: /h2
      #进行该配置，程序开启时就会启动h2 web consloe。当然这是默认的，如果你不想在启动程序时启动h2 web consloe，那么就设置为false。
      enabled: true

      # 配置日志打印信息
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
