INSERT INTO USER (USER_ID,USER_NAME,USER_AGE,CREATE_TIME,MODIFY_TIME,USER_STATUS) VALUES(
1,'赵一',20,sysdate,sysdate,'0');
INSERT INTO USER (USER_ID,USER_NAME,USER_AGE,CREATE_TIME,MODIFY_TIME,USER_STATUS) VALUES(
2,'赵二',20,sysdate,sysdate,'0');
