spring:
  application:
    name: order-service
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tcc_cap?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    tempalte-loader-path: classpath:/templates
    settings:
      number_format: 0
dubbo:
  application:
    id: order-service #dubbo提供者的别名，只是个标识
  base-package: org.mengyun # dubbo服务发布者所在的包
  registry:
    address: zookeeper://127.0.0.1:2181 # zookeeper注册中心的地址
    port: 2181       # zookeeper注册中心的端口
    protocol: zookeeper
    register: true
    timeout: 120000
    session: 180000
  protocol:
    name: dubbo #dubbo协议
    port: 20885 #duboo端口号
    accesslog: true
  provider:
    retries: 1
    delay: -1
server:
  port: 8085

