server:
  port: 8006
spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: 127.0.0.1:9092
    bootstrap-servers:  127.0.0.1:9092
    topic:
      Name: home.bus.log #自定义topic名称
      numPartitions: 2  #自定义分区
      replicationFactor: 2 #自定义副本
    consumer:
      group-id: home.bus.log.group.1
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 20000ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer