spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti007?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&nullCatalogMeansCurrent=true
    username : root
    password : 123456
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
    database-schema-update: true
server:
  port: 8086
