server:
  port: 8761              # Eureka实例的端口
eureka:
  client:
    # 设置是否将自己作为客户端注册到注册中心（缺省true）
    # 这里为不需要（查看@EnableEurekaServer注解的源码，会发现它间接用到了@EnableDiscoveryClient）
    registerWithEureka: false
    # 设置是否从注册中心获取注册信息（缺省true）
    # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:123@127.0.0.1:8761/eureka/ # https://yq.aliyun.com/articles/98348?t=t1
