CREATE DATABASE `TCC` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE TABLE `TCC_TRANSACTION` (
  `TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '事务 ID',
  `DOMAIN` varchar(100) DEFAULT NULL COMMENT '域名',
  `GLOBAL_TX_ID` varbinary(32) NOT NULL COMMENT '全局事务ID',
  `BRANCH_QUALIFIER` varbinary(32) NOT NULL,
  `CONTENT` varbinary(8000) DEFAULT NULL COMMENT '序列化 Transaction 事务内容',
  `STATUS` int(11) DEFAULT NULL COMMENT '事务状态',
  `TRANSACTION_TYPE` int(11) DEFAULT NULL COMMENT '事务类型',
  `RETRIED_COUNT` int(11) DEFAULT NULL COMMENT '重试次数',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `VERSION` int(11) DEFAULT NULL COMMENT '乐观锁版本',
  `IS_DELETE` int(12) DEFAULT NULL COMMENT '是否删除',
  PRIMARY KEY (`TRANSACTION_ID`),
  UNIQUE KEY `UX_TX_BQ` (`GLOBAL_TX_ID`,`BRANCH_QUALIFIER`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `TCC_TRANSACTION_CAP` (
  `TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '事务 ID',
  `DOMAIN` varchar(100) DEFAULT NULL COMMENT '域名',
  `GLOBAL_TX_ID` varbinary(32) NOT NULL COMMENT '全局事务ID',
  `BRANCH_QUALIFIER` varbinary(32) NOT NULL,
  `CONTENT` varbinary(8000) DEFAULT NULL COMMENT '序列化 Transaction 事务内容',
  `STATUS` int(11) DEFAULT NULL COMMENT '事务状态',
  `TRANSACTION_TYPE` int(11) DEFAULT NULL COMMENT '事务类型',
  `RETRIED_COUNT` int(11) DEFAULT NULL COMMENT '重试次数',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `VERSION` int(11) DEFAULT NULL COMMENT '乐观锁版本',
  `IS_DELETE` int(12) DEFAULT NULL COMMENT '是否删除',
  PRIMARY KEY (`TRANSACTION_ID`),
  UNIQUE KEY `UX_TX_BQ` (`GLOBAL_TX_ID`,`BRANCH_QUALIFIER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TCC_TRANSACTION_ORD` (
  `TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '事务 ID',
  `DOMAIN` varchar(100) DEFAULT NULL COMMENT '域名',
  `GLOBAL_TX_ID` varbinary(32) NOT NULL COMMENT '全局事务ID',
  `BRANCH_QUALIFIER` varbinary(32) NOT NULL,
  `CONTENT` varbinary(8000) DEFAULT NULL COMMENT '序列化 Transaction 事务内容',
  `STATUS` int(11) DEFAULT NULL COMMENT '事务状态',
  `TRANSACTION_TYPE` int(11) DEFAULT NULL COMMENT '事务类型',
  `RETRIED_COUNT` int(11) DEFAULT NULL COMMENT '重试次数',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `VERSION` int(11) DEFAULT NULL COMMENT '乐观锁版本',
  `IS_DELETE` int(12) DEFAULT NULL COMMENT '是否删除',
  PRIMARY KEY (`TRANSACTION_ID`),
  UNIQUE KEY `UX_TX_BQ` (`GLOBAL_TX_ID`,`BRANCH_QUALIFIER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TCC_TRANSACTION_RED` (
  `TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '事务 ID',
  `DOMAIN` varchar(100) DEFAULT NULL COMMENT '域名',
  `GLOBAL_TX_ID` varbinary(32) NOT NULL COMMENT '全局事务ID',
  `BRANCH_QUALIFIER` varbinary(32) NOT NULL,
  `CONTENT` varbinary(8000) DEFAULT NULL COMMENT '序列化 Transaction 事务内容',
  `STATUS` int(11) DEFAULT NULL COMMENT '事务状态',
  `TRANSACTION_TYPE` int(11) DEFAULT NULL COMMENT '事务类型',
  `RETRIED_COUNT` int(11) DEFAULT NULL COMMENT '重试次数',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `VERSION` int(11) DEFAULT NULL COMMENT '乐观锁版本',
  `IS_DELETE` int(12) DEFAULT NULL COMMENT '是否删除',
  PRIMARY KEY (`TRANSACTION_ID`),
  UNIQUE KEY `UX_TX_BQ` (`GLOBAL_TX_ID`,`BRANCH_QUALIFIER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `TCC_TRANSACTION_UT` (
  `TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOMAIN` varchar(100) DEFAULT NULL,
  `GLOBAL_TX_ID` varbinary(32) NOT NULL,
  `BRANCH_QUALIFIER` varbinary(32) NOT NULL,
  `CONTENT` varbinary(8000) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  `TRANSACTION_TYPE` int(11) DEFAULT NULL,
  `RETRIED_COUNT` int(11) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `LAST_UPDATE_TIME` datetime DEFAULT NULL,
  `VERSION` int(11) DEFAULT NULL,
  PRIMARY KEY (`TRANSACTION_ID`),
  UNIQUE KEY `UX_TX_BQ` (`GLOBAL_TX_ID`,`BRANCH_QUALIFIER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
