spring:图形界面
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/mybt1?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    continue-on-error: true
    sql-script-encoding: UTF-8
    password: 123456
    data-username: root
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      jdbc-url: jdbc:mysql://127.0.0.1:3306/mybt1?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
      username: root
      password: 123456
      allow-pool-suspension: true
      auto-commit: true
      idle-timeout: 300000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 300000
      connection-test-query: SELECT 1
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  config-location: classpath:/config/mybatis-config.xml
server:
  port: 8089
#mybatis:
#  configuration:
#    cache-enabled: true
#    lazy-loading-enabled: true
#    aggressive-lazy-loading: false
#    multiple-result-sets-enabled: true
#    use-column-label: true
#    use-generated-keys: false
#    auto-mapping-behavior: partial
#    default-executor-type: simple
#    default-statement-timeout: 2500
#    default-fetch-size: 25
#    safe-row-bounds-enabled: false
#    map-underscore-to-camel-case: true
#    localCacheScope: statement
#    jdbcTypeForNull: null
#    #lazyLoadTriggerMethods: null
#    callSettersOnNulls: true
#  #    #configuration-factory: para.cic.idm.core.mybatis.MybatisConfiguration
#  #  config-location: classpath:/mybatis/mybatis-config.xml
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:/mybatis-mapper/*Mapper.xml
